#!/usr/bin/env python3

import sys
import json
import subprocess
import os
import shutil

def run():
    _, metadata_path, pdf_path = sys.argv
    with open(metadata_path) as f:
        metadata = json.load(f)

    metadata_dir = os.path.join(".", "pdf_to_book_reader",
                                str(metadata['product_id']))
    metadata_dst = os.path.join(metadata_dir,
                                "book_metadata.json")

    if not os.path.exists(metadata_dir):
        os.mkdir(metadata_dir)
    shutil.copy(metadata_path, metadata_dst)

    exe = "make"
    args = [ exe,
        "PRODUCT_ID=" + str(metadata['product_id']),
        "TITLE=" + metadata['title'],
        "BLURB=" + metadata['blurb'],
        "PDF_PATH=" + pdf_path
    ]

    os.chdir(os.path.dirname(__file__))
    os.chdir("pdf_to_book_reader")
    sys.exit(os.execvp(exe, args))

if __name__ == '__main__':
    run()
