#!/usr/bin/env python3

import sys
import json
import subprocess
import os

def run():
    _, metadata_path, pdf_path = sys.argv
    with open(metadata_path) as f:
        metadata = json.load(f)

    exe = "./example_tgmsbf.sh"
    args = [ exe,
        "-c", str(metadata['product_id']),
        "-b", metadata['title'],
        "-d", metadata['blurb'],
        "-i", pdf_path
    ]

    os.chdir(os.path.dirname(__file__))
    os.chdir("pdf_to_book_reader")
    sys.exit(os.execv(exe, args))

if __name__ == '__main__':
    run()
